front:
  build: images/nginx
  ports:
    - "80:80"
    - "9000:9000"
  links:
    - memcached:memcached
  volumes:
    - /var/www:/var/www

memcached:
  image: tutum/memcached
  ports:
    - "11211:11211"
  environment:
    MEMCACHED_PASS: 12347890
